version: "3.1"
services:
  app:
    build: ./server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080
    links:
      - mongo
  static:
    build: ./client
    ports:
      - 8000
    volumes:
      - ./client:/usr/src/static
      - /usr/src/static/node_modules
  mongo:
    image: mongo
    ports:
      - 27017
  nginx:
    build: ./nginx
    links:
      - app:app
      - static:static
    ports:
      - 80:80

